---
- hosts: all
  become: true

  tasks:
  - name: Stop running docker container
    command: docker stop ashwins-container
    ignore_errors: yes

  - name: Remove docker container
    command: docker container rm ashwins-container
    ignore_errors: yes

  - name: Remove docker image
    command: docker rmi ashwinpagarkhed/deployjava
    ignore_errors: yes

  - name: Build the image from Dockerfile
    command: docker build -t ashwinpagarkhed/deployjava .
    args:
      chdir: /opt/docker

  - name: Push the image to Dockerhub
    command: docker push ashwinpagarkhed/deployjava

  - name: Run the image
    command: docker run -d --name ashwins-container -p 8080:8080 ashwinpagarkhed/deployjava:latest











