---
- hosts: all
  become: true
  tasks:
  - name: Stop all docker containers
    shell: docker kill $(docker ps -q)
    ignore_errors: yes

  - name: Remove all docker containers
    shell: docker container rm $(sudo docker ps -a)
    ignore_errors: yes

  - name: Remove all docker images
    shell: docker rmi $(docker images -a -q)
    ignore_errors: yes

  - name: Build the image from Dockerfile
    shell: docker build -t ashwinpagarkhed/deployjava .

  - name: Push the image to Dockerhub
    shell: docker push ashwinpagarkhed/deployjava

  - name: Run the container
    shell: docker run -d -it -p 8080:8080 ashwinpagarkhed/deployjava:latest