---
- hosts: all
  become: true
  tasks:
  - name: Stop all docker containers
    shell: sudo docker kill $(sudo docker ps -q)
  - name: Remove all docker containers
    shell: sudo docker container rm $(sudo docker ps -a)
  - name: Remove all docker images
    shell: sudo docker rmi $(sudo docker images -a -q)
  - name: Build the image from Dockerfile
    shell: sudo docker build -t ashwinpagarkhed/deployjava .
  - name: Push the image to Dockerhub
    shell: sudo docker push ashwinpagarkhed/deployjava
  - name: Run the container
    shell: sudo docker run -d -it -p 8080:8080 ashwinpagarkhed/deployjava:latest