---
- hosts: all
  become: true

  tasks:
  - name: Removing previous image
    command: docker rmi ashwinpagarkhed/deployjava
    ignore_errors: yes

  - name: Build the image from Dockerfile
    command: docker build -t ashwinpagarkhed/deployjava .
    args:
      chdir: /opt/docker 

  - name: Push the image to Dockerhub
    command: docker push ashwinpagarkhed/deployjava